In [1]:
#f = open('/home/shashank/workspace/Statistics_and_Machine_Learning/Statistics-and-Machine-Learning/trainingAndTest/training-and-test/training.json', "r")

strip is used to reme white spaces like '\n' 
split is used to convert it into list

In [10]:
# import json
# data={}
# students=0
# count=0
# for i in f:
#     if count==0:
#         students=int(i.strip())
#         count+=1
#     else:
#         data[json.loads(i.strip())['serial']]=json.loads(i.strip())  
#         count+=1

In [7]:
import pandas as pd
df=pd.DataFrame(data)

In [9]:
#df.to_csv('school_data.csv')

In [15]:
df.T.corr()

,Accountancy,Biology,BusinessStudies,Chemistry,ComputerScience,Economics,English,Mathematics,PhysicalEducation,Physics,serial
Accountancy,1.000000,NaN,0.649718,0.614151,0.445796,0.679753,0.502118,0.684171,0.447006,0.815446,0.022595
Biology,NaN,1.000000,NaN,0.678521,NaN,NaN,0.466226,0.574887,0.197489,0.694336,-0.001295
BusinessStudies,0.649718,NaN,1.000000,0.000000,0.548860,0.657774,0.591130,0.604873,0.394378,0.470777,0.012560
Chemistry,0.614151,0.678521,0.000000,1.000000,0.679314,0.668026,0.454287,0.719888,0.429793,0.769097,-0.007622
ComputerScience,0.445796,NaN,0.548860,0.679314,1.000000,-0.058824,0.448686,0.671067,0.159149,0.683973,-0.003668
Economics,0.679753,NaN,0.657774,0.668026,-0.058824,1.000000,0.534937,0.649873,0.661018,0.685069,0.006992
English,0.502118,0.466226,0.591130,0.454287,0.448686,0.534937,1.000000,0.427342,0.405199,0.504840,-0.001261
Mathematics,0.684171,0.574887,0.604873,0.719888,0.671067,0.649873,0.427342,1.000000,0.394282,0.717532,-0.001909
PhysicalEducation,0.447006,0.197489,0.394378,0.429793,0.159149,0.661018,0.405199,0.394282,1.000000,0.429112,-0.003521
Physics,0.815446,0.694336,0.470777,0.769097,0.683973,0.685069,0.504840,0.717532,0.429112,1.000000,-0.005177
serial,0.022595,-0.001295,0.012560,-0.007622,-0.003668,0.006992,-0.001261,-0.001909,-0.003521,-0.005177,1.000000

In [20]:
df.T.drop("serial")

KeyError: "['serial'] not found in axis"